# Generated by Django 4.0.6 on 2022-07-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treebanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.TextField()),
                ('search_completed', models.DateTimeField(editable=False, null=True)),
                ('last_accessed', models.DateField(editable=False, null=True)),
                ('results', models.TextField(default='', editable=False)),
                ('number_of_results', models.PositiveIntegerField(editable=False, null=True)),
                ('completed_part', models.PositiveIntegerField(editable=False, help_text='Total size in KiB of databases for which the search has been completed', null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treebanks.component')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.TextField()),
                ('total_database_size', models.PositiveIntegerField(editable=False, help_text='Total size in KiB of all databases for this query', null=True)),
                ('completed_part', models.PositiveIntegerField(editable=False, help_text='Total size in KiB of databases for which the search has been completed', null=True)),
                ('components', models.ManyToManyField(to='treebanks.component')),
                ('results', models.ManyToManyField(editable=False, to='search.componentsearchresult')),
            ],
        ),
    ]
