# Generated by Django 4.1 on 2022-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsearchresult',
            name='errors',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddConstraint(
            model_name='componentsearchresult',
            constraint=models.UniqueConstraint(fields=('xpath', 'component'), name='componentsearchresult_uniqueness'),
        ),
    ]
