# Generated by Django 4.0.6 on 2022-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsearchresult',
            name='elapsed_time',
            field=models.PositiveBigIntegerField(editable=False, help_text='Elapsed time in ms', null=True),
        ),
        migrations.AddField(
            model_name='componentsearchresult',
            name='errors',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddConstraint(
            model_name='componentsearchresult',
            constraint=models.UniqueConstraint(fields=('xpath', 'component'), name='componentsearchresult_uniqueness'),
        ),
    ]
