# Generated by Django 4.1 on 2022-08-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_componentsearchresult_componentsearchresult_uniqueness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='True if the query was cancelled by the user'),
        ),
    ]
