<?php
/**
 * Looks up an XML tree in a BaseX database and prints it as a syntax tree.
 *
 * This file is called when a user clicks a link on the results page. The links
 * are generated by php/flush-results.php and php/get-all-results.php and parsed
 * in js/results.js.
 *
 * @version 1.0  date: 08.30.2016  converted xml2tree.pl to PHP function
 * @version 0.5  date: 05.22.2016  removed `opt` GET. Not necessary for this build
 * @version 0.4  date: 14.10.2014  RELEASED WITH GrETEL2.0
 *
 * @author Liesbeth Augustinus
 * @author Bram Vanroy
 */
require_once ROOT_PATH.'/basex-search-scripts/basex-client.php';

function showTree($sentid, $treebank, $db)
{
    global $dbuser, $dbpwd;
    header('Content-type: text/xml');
    header('Access-Control-Allow-Origin: *');
    set_time_limit(0);

    try {
        $serverInfo;
        if (isGrinded($treebank)) {
            preg_match('/^([A-Z]{5})/', $db, $component);
            $serverInfo = getServerInfo($treebank, $component[0]);
            $queryPath = $db;
        } else {
            $serverInfo = getServerInfo($treebank, false);
            $queryPath = strtoupper($treebank);
            $queryPath .= '_ID';
        }

        $dbhost = $serverInfo['machine'];
        $dbport = $serverInfo['port'];
        $session = new Session($dbhost, $dbport, $dbuser, $dbpwd);
        $xquery = 'db:open("'.$queryPath.'")/treebank/alpino_ds[@id="'.$sentid.'"]';
        $query = $session->query($xquery);
        $xml = $query->execute();

        echo $xml;
    } catch (Exception $e) {
        http_response_code(500);
        echo $e->getMessage();
    }
}
