// based on https://www.let.rug.nl/vannoord/Lassy/sa-man_lassy.pdf and https://github.com/rug-compling/paqu/blob/master/src/pqserve/attributes.txt
type XPathAttribute = {
    description: string,
    /**
     * [value, description][]
     */
    values: [string, string][]
}

export let XpathAttributes: { [name: string]: XPathAttribute } = {
    'aform': { description: '', values: [] },
    'begin': { description: 'Begin position', values: [] },
    'buiging': { description: '', values: [] },
    'case': {
        description: 'Finite verb case',
        values: [
            ['nom', 'Nominative'],
            ['acc', 'Accusative'],
            ['nom_acc', 'Nominative | Accusative'],
            ['gen', 'Genitive'],
            ['dat', 'Dative'],
            ['dat_acc', 'Dative | Accusative'],
            ['obl', ''],
            ['no_obl', ''],
            ['both', '']
        ]
    },
    'cat': { description: 'Category', values: [] },
    'comparative': {
        description: 'Comparative',
        values: [
            ['dan',''],
            ['als', ''],
            ['dat', ''], 
            ['om', ''],
            ['e_als', '"zoveel"']
        ]
    },
    'conjtype': { description: '', values: [] },
    'def': {
        description: 'Article definiteness',
        values: [
            ['def', ''],
            ['indef', ''],
            ['both', '']]
    },
    'dial': { description: '', values: [] },
    'end': { description: 'End position', values: [] },
    'frame': { description: 'Full lexical category', values: [] },
    'gen': {
        description: 'Gender', values: [
            ['de', ''],
            ['het', ''],
            ['both', '']
        ]
    },
    'genus': { description: '', values: [] },
    'getal': { description: '', values: [] },
    'getal-n': { description: '', values: [] },
    'graad': { description: '', values: [] },
    'his': { description: '', values: [] },
    'his_1': { description: '', values: [] },
    'his_2': { description: '', values: [] },
    'his_1_1': { description: '', values: [] },
    'his_1_2': { description: '', values: [] },
    'his_2_1': { description: '', values: [] },
    'his_2_2': { description: '', values: [] },
    'his_1_1_1': { description: '', values: [] },
    'his_1_1_2': { description: '', values: [] },
    'his_1_2_1': { description: '', values: [] },
    'his_1_2_2': { description: '', values: [] },
    'his_2_1_1': { description: '', values: [] },
    'his_2_1_2': { description: '', values: [] },
    'his_2_2_1': { description: '', values: [] },
    'his_2_2_2': { description: '', values: [] },
    'id': { description: '', values: [] },
    'iets': { description: '', values: [] },
    'index': { description: 'Node index', values: [] },
    'infl': {
        description: 'Inflection of (ad)verb',
        values: [
            ['sg', 'Verb | Det'],
            ['sg1', 'Verb'],
            ['sg3', 'Verb'],
            ['sg_heeft', 'Verb'],
            ['sg_hebt', 'Verb'],
            ['modal_u', 'Verb'],
            ['modal_inv', 'Verb'],
            ['pl', 'Verb | Det'],
            ['imp(sg1)', 'Verb'],
            ['imp(modal_u) subjunctive', 'Verb'],
            ['psp', 'Verb'],
            ['inf', 'Verb'],
            ['inf(e)', 'Verb'],
            ['inf(no_e)', 'Verb'],
            ['inf_ipp', 'Verb'],
            ['e', 'Adj'],
            ['no_e', 'Adj'],
            ['er', 'Adj'],
            ['both', 'Adj | Det | Number'],
            ['pred', 'Adj'],
            ['anders', 'Adj'],
            ['ge_e', 'Adj'],
            ['ge_no_', 'Adj'],
            ['ge_both', 'Adj'],
            ['stof', 'Adj'],
            ['postn_no_e', 'Adj'],
            ['postn_e', 'Adj'],
            ['postn_both', 'Adj'],
            ['meer', 'Adj'],
            ['ere', 'Adj'],
            ['ste', 'Adj'],
            ['st', 'Adj'],
            ['het_st', 'Adj'],
            ['end', 'Adj'],
            ['ende', 'Adj'],
            ['sten', 'Adj'],
            ['eren', 'Adj'],
            ['de', 'Det'],
            ['het', 'Det'],
            ['een', 'Det'],
            ['pron', 'Det'],
            ['geen', 'Det'],
            ['pl_num', 'Det | Number'],
            ['alle', 'Det'],
            ['enkele', 'Det'],
            ['wat', 'Det'],
            ['welke', 'Det'],
            ['elke', 'Det'],
            ['der', 'Det'],
            ['pl_indef', 'Det'],
            ['al', 'Det'],
            ['enkel', 'Det'],
            ['zulke', 'Det'],
            ['welk', 'Det'],
            ['den', 'Det'],
            ['des', 'Det'],
            ['sg_num', 'Det | Number']
        ]
    },
    'lcat': { description: 'Complementized category', values: [] },
    'lemma': { description: 'Word lemma', values: [] },
    'lwtype': { description: '', values: [] },
    'mwu_root': { description: '', values: [] },
    'mwu_sense': { description: '', values: [] },
    'naamval': { description: '', values: [] },
    'neclass': {
        description: 'Named entity class',
        values: [
            ['LOC', 'Location'],
            ['PER', 'Person'],
            ['ORG', 'Organization'],
            ['MISC', 'Miscellaneous'],
            ['year', 'Year']
        ]
    },
    'npagr': { description: '', values: [] },
    'ntype': { description: '', values: [] },
    'num': {
        description: 'Number',
        values: [
            ['sg', ''],
            ['pl', ''],
            ['both', ''],
            ['meas', ''],
            ['bare_meas', ''],
            ['pl_num', ''],
            ['sg_num', '']
        ]
    },
    'numtype': { description: '', values: [] },
    'other_id': { description: '', values: [] },
    'pb': { description: '', values: [] },
    'pdtype': { description: '', values: [] },
    'per': {
        description: 'Person',
        values: [
            ['u', ''],
            ['both', ''],
            ['fir', ''],
            ['inv', ''],
            ['je', ''],
            ['thi', ''],
            ['u_thi', '']
        ]
    },
    'personalized': { description: '', values: [] },
    'persoon': { description: '', values: [] },
    'pos': {
        description: 'Simplified POS-tag',
        values: [
            ['noun', ''],
            ['name', ''],
            ['punct', ''],
            ['det', ''],
            ['prep', ''],
            ['verb', ''],
            ['adj', ''],
            ['adv', ''],
            ['vg', ''],
            ['num', ''],
            ['pron', ''],
            ['comp', ''],
            ['part', ''],
            ['pp', ''],
            ['fixed', ''],
            ['tag', ''],
            ['comparative', ''],
            ['prefix', ''],
            ['etc', ''],
            ['max', ''],
            ['- -', 'Not analyzed'],
            ['UNKNOWN', 'Parse problem']
        ]
    },
    'positie': { description: '', values: [] },
    'postag': { description: '', values: [] },
    'pron': { description: '', values: [] },
    'pt': { description: '', values: [] },
    'pvagr': { description: '', values: [] },
    'pvtijd': { description: '', values: [] },
    'refl': { description: '', values: [] },
    'rel': { description: 'Dependency relation', values: [] },
    'rnum': { description: '', values: [] },
    'root': { description: 'Root form', values: [] },
    'sc': { description: 'Sub-categorization frame', values: [] },
    'sense': { description: 'Word sense', values: [] },
    'special': { description: '', values: [] },
    'spectype': { description: '', values: [] },
    'status': { description: '', values: [] },
    'stype': { description: '', values: [] },
    'tense': { description: 'Word tense', values: [['past', '']] },
    'vform': { description: '', values: [] },
    'vwtype': { description: '', values: [] },
    'vztype': { description: '', values: [] },
    'wh': {
        description: 'Question word',
        values: [
            ['ywh', ''],
            ['nwh', ''],
            ['rwh', ''],
            ['wh', ''],
            ['rel', '']
        ]
    },
    'wk': { description: '', values: [] },
    'word': { description: 'Surface form', values: [] },
    'word_is_': { description: '', values: [] },
    'wvorm': { description: '', values: [] },
}
