# Generated by Django 4.0.6 on 2022-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwe', '0003_xpathquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xpathquery',
            old_name='query',
            new_name='xpath',
        ),
        migrations.AlterField(
            model_name='canonicalform',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
