# Generated by Django 4.1.2 on 2022-10-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwe', '0004_rename_query_xpathquery_xpath_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xpathquery',
            options={'verbose_name': 'XPath Query', 'verbose_name_plural': 'XPath Queries'},
        ),
    ]
