<?php
/**
 * Looks up an XML tree in a BaseX database and prints it as a syntax tree.
 *
 * This file is called when a user clicks a link on the results page. The links
 * are generated by php/flush-results.php and php/get-all-results.php and parsed
 * in js/results.js.
 *
 * @version 0.5  date: 05.22.2016  removed `opt` GET. Not necessary for this build
 * @version 0.4  date: 14.10.2014  RELEASED WITH GrETEL2.0
 *
 * @author Liesbeth Augustinus
 * @author Bram Vanroy
 */

// Set variables
if (isset($_GET['sid'])) {
    $sentid = $_GET['sid'];
}
if (isset($_GET['id'])) {
    $idstring = $_GET['id'];
}
if (isset($_GET['wd'])) {
    $wstring = $_GET['wd'];
}
if (isset($_GET['tb'])) {
    $treebank = $_GET['tb'];
}
if (isset($_GET['db'])) {
    $db = $_GET['db'];
}

require '../config/config.php';
require "$scripts/BaseXClient.php";

//header('Content-type: text/xml');

try {
    if ($treebank == 'sonar') {
        preg_match('/^([A-Z]{5})/', $db, $component);
        $dbhost = $dbnameServerSonar[$component[0]];
        $session = new Session($dbhost, $dbportSonar, $dbuserSonar, $dbpwdSonar);
        $queryPath = $db;
    } else {
        $session = new Session($dbhost, $dbport, $dbuser, $dbpwd);
        $queryPath = strtoupper($treebank);
        $queryPath .= '_ID';
    }

    $xquery = 'db:open("'.$queryPath.'")/treebank/alpino_ds[@id="'.$sentid.'"]';
    $query = $session->query($xquery);
    $xml = $query->execute();

    $query->close();
    $session->close();

    $xml = strtr($xml, "'", '&apos;');

    // build xpath
    if (isset($idstring)) {
        $part = preg_replace('/(\d+)/', '@id="$1"', $idstring);
        $xpart = str_replace('-', ' or ', $part);
        $xpath = "//node[$xpart]";
    } elseif (isset($wstring)) {
        $wstring = preg_replace('/^-*|-*$/', '', $wstring);
        $part = preg_replace('/(\w+)/', '@word="$1" or @lemma="$1"', $wstring);
        $xpart = str_replace('-', ' or ', $part);
        $xpath = "//node[$xpart]";
    } else {
        $xpath = '//node[@rel="--"]';
    }


    $styletree = `perl $scripts/xml2tree.pl '$xml' '$xpath'`;
    $stylexml = simplexml_load_string($styletree);
    echo $stylexml->asXML();
} catch (Exception $e) {
    echo $e->getMessage();
}
