# Generated by Django 4.0.6 on 2022-07-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basexdb',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='treebanks.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='treebank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='treebanks.treebank'),
        ),
    ]
