# Generated by Django 4.1 on 2022-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0002_remove_component_total_database_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='treebank',
            name='groups',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='treebank',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
