# Generated by Django 4.1.2 on 2022-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0003_component_group_component_variant_treebank_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='contains_metadata',
            field=models.BooleanField(default=False),
        ),
    ]
