# Generated by Django 4.1.2 on 2022-10-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0003_component_contains_metadata'),
        ('treebanks', '0003_component_group_component_variant_treebank_groups_and_more'),
    ]

    operations = [
    ]
